version: 2

orbs:
  heroku: circleci/heroku@1.0.0

jobs:
  build:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            
            # fallback
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # - run: yarn test
  # deploy:
  #   docker:
  #     - image: buildpack-deps:trusty
  #   steps:
  #     - checkout
  #     - run:
  #         name: Deploy Master to Heroku
  #         command: |
  #           git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
  heroku_deploy:
    executor: heroku/default
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: "${HEROKU_APP_NAME}"
      - run:
          name: DB migrations
          command: heroku run --app "${HEROKU_APP_NAME}" "yarn db:migrate"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - heroku_deploy:
          requires:
            - build
          filters:
            branches:
              only: master